import { eq } from "drizzle-orm";
import { getDb } from "./index";
import { equipmentItems, exercises, orgEquipment, organizations } from "./schema";
import {
  EXERCISE_CUES,
  EXERCISE_DESCRIPTIONS,
  EXERCISE_SECONDARY,
} from "./exercise-cues";
import {
  defaultExerciseCues,
  defaultExerciseDescription,
} from "@/lib/exercise-meta";
import { id } from "@/lib/utils";

type EqDef = {
  slug: string;
  name: string;
  pattern: string;
  muscles: string;
  secondary?: string;
  difficulty?: string;
  tags: string;
  cues?: string;
  description?: string;
  /** equipment slugs; empty = bodyweight */
  equipment: string[];
  equipmentAny?: boolean;
};

type EquipDef = {
  slug: string;
  name: string;
  category: string;
  /** Integer sort key (equipment_items.sort_order is INTEGER) */
  sort: number;
  description?: string;
};

const EQUIPMENT: EquipDef[] = [
  // Bodyweight / free
  {
    slug: "bodyweight",
    name: "Bodyweight only",
    category: "bodyweight",
    sort: 0,
    description: "No external load — always available.",
  },
  // Free weights
  {
    slug: "dumbbell",
    name: "Dumbbells",
    category: "free_weights",
    sort: 1,
    description: "Pairs or rack; covers most unilateral and bilateral DB work.",
  },
  {
    slug: "barbell",
    name: "Barbell + plates",
    category: "free_weights",
    sort: 2,
    description: "Olympic or standard bar with plates for compound loading.",
  },
  {
    slug: "kettlebell",
    name: "Kettlebells",
    category: "free_weights",
    sort: 3,
    description: "Swings, goblets, carries, and Turkish get-ups.",
  },
  {
    slug: "trap-bar",
    name: "Trap / hex bar",
    category: "free_weights",
    sort: 4,
    description: "Deadlifts and shrugs with a more upright torso option.",
  },
  {
    slug: "ez-bar",
    name: "EZ curl bar",
    category: "free_weights",
    sort: 5,
    description: "Curls and skull-crushers with a friendlier wrist angle.",
  },
  {
    slug: "weight-plate",
    name: "Weight plates",
    category: "free_weights",
    sort: 6,
    description: "Loading, plate holds, pinches, and heel elevators.",
  },
  {
    slug: "sandbox-bag",
    name: "Sandbag",
    category: "free_weights",
    sort: 7,
    description: "Odd-object loading for carries, cleans, and conditioning.",
  },
  {
    slug: "swiss-bar",
    name: "Swiss / multi-grip bar",
    category: "free_weights",
    sort: 8,
    description: "Neutral-grip pressing and rows for shoulder comfort.",
  },
  // Machines
  {
    slug: "cable",
    name: "Cable / functional trainer",
    category: "machines",
    sort: 10,
    description: "Adjustable pulleys for rows, flyes, face pulls, and chops.",
  },
  {
    slug: "lat-pulldown",
    name: "Lat pulldown",
    category: "machines",
    sort: 11,
    description: "Vertical pull when pull-ups are limited.",
  },
  {
    slug: "seated-row",
    name: "Seated row machine",
    category: "machines",
    sort: 12,
    description: "Supported horizontal pull variations.",
  },
  {
    slug: "chest-press-machine",
    name: "Chest press machine",
    category: "machines",
    sort: 13,
    description: "Guided horizontal press for beginners or high volume.",
  },
  {
    slug: "shoulder-press-machine",
    name: "Shoulder press machine",
    category: "machines",
    sort: 14,
    description: "Guided vertical press.",
  },
  {
    slug: "pec-deck",
    name: "Pec deck / rear delt",
    category: "machines",
    sort: 15,
    description: "Flye and reverse flye machine.",
  },
  {
    slug: "leg-press",
    name: "Leg press",
    category: "machines",
    sort: 16,
    description: "High-load lower body without axial spine load.",
  },
  {
    slug: "hack-squat",
    name: "Hack squat",
    category: "machines",
    sort: 17,
    description: "Guided squat pattern for quads / knees.",
  },
  {
    slug: "leg-extension",
    name: "Leg extension",
    category: "machines",
    sort: 18,
    description: "Quad isolation and knee-friendly work.",
  },
  {
    slug: "leg-curl",
    name: "Leg curl (lying / seated)",
    category: "machines",
    sort: 19,
    description: "Hamstring isolation.",
  },
  {
    slug: "hip-abductor",
    name: "Hip abductor",
    category: "machines",
    sort: 20,
    description: "Lateral hip / glute med machine.",
  },
  {
    slug: "hip-adductor",
    name: "Hip adductor",
    category: "machines",
    sort: 21,
    description: "Inner thigh machine.",
  },
  {
    slug: "calf-raise-machine",
    name: "Calf raise machine",
    category: "machines",
    sort: 22,
    description: "Standing or seated calf loading.",
  },
  {
    slug: "smith",
    name: "Smith machine",
    category: "machines",
    sort: 23,
    description: "Fixed-path bar for guided compounds.",
  },
  {
    slug: "assisted-pullup",
    name: "Assisted pull-up / dip",
    category: "machines",
    sort: 24,
    description: "Counterweight help for vertical push/pull skill.",
  },
  {
    slug: "cable-crossover",
    name: "Cable crossover station",
    category: "machines",
    sort: 25,
    description: "Dual high/low cables for flyes and angles.",
  },
  {
    slug: "preacher-curl",
    name: "Preacher curl bench/machine",
    category: "machines",
    sort: 26,
    description: "Supported biceps isolation.",
  },
  {
    slug: "t-bar-row",
    name: "T-bar row station",
    category: "machines",
    sort: 27,
    description: "Chest-supported or landmine-style rows.",
  },
  // Accessories / stations
  {
    slug: "pullup-bar",
    name: "Pull-up bar",
    category: "accessories",
    sort: 30,
    description: "Chin-ups, pull-ups, hangs.",
  },
  {
    slug: "dip-bars",
    name: "Dip bars / parallel bars",
    category: "accessories",
    sort: 31,
    description: "Dips and support holds.",
  },
  {
    slug: "bench",
    name: "Flat / adjustable bench",
    category: "accessories",
    sort: 32,
    description: "Presses, rows, hip thrusts, step-ups.",
  },
  {
    slug: "rack",
    name: "Squat / power rack",
    category: "accessories",
    sort: 33,
    description: "Safe barbell squats, presses, and pulls.",
  },
  {
    slug: "bands",
    name: "Resistance / mini-bands",
    category: "accessories",
    sort: 34,
    description: "Warm-ups, activation, assisted or resisted patterns.",
  },
  {
    slug: "foam-roller",
    name: "Foam roller",
    category: "accessories",
    sort: 35,
    description: "Self-massage and thoracic extension.",
  },
  {
    slug: "lacrosse-ball",
    name: "Lacrosse / massage ball",
    category: "accessories",
    sort: 36,
    description: "Targeted soft-tissue work.",
  },
  {
    slug: "medicine-ball",
    name: "Medicine ball",
    category: "accessories",
    sort: 37,
    description: "Throws, slams, rotational power (non-bounce or bounce).",
  },
  {
    slug: "slam-ball",
    name: "Slam ball",
    category: "accessories",
    sort: 38,
    description: "Dead-bounce ball for slams and conditioning.",
  },
  {
    slug: "landmine",
    name: "Landmine attachment",
    category: "accessories",
    sort: 39,
    description: "Angled presses, rows, and squats — shoulder-friendly options.",
  },
  {
    slug: "suspension",
    name: "TRX / suspension trainer",
    category: "accessories",
    sort: 40,
    description: "Scalable bodyweight rows, presses, and core.",
  },
  {
    slug: "box",
    name: "Plyo / step box",
    category: "accessories",
    sort: 41,
    description: "Step-ups, box squats, jumps, and elevated push-ups.",
  },
  {
    slug: "sled",
    name: "Sled / prowler",
    category: "accessories",
    sort: 42,
    description: "Pushes, drags, and conditioning with low eccentric cost.",
  },
  {
    slug: "battle-ropes",
    name: "Battle ropes",
    category: "accessories",
    sort: 43,
    description: "Upper-body conditioning waves and slams.",
  },
  {
    slug: "ab-wheel",
    name: "Ab wheel",
    category: "accessories",
    sort: 44,
    description: "Anti-extension core rollouts.",
  },
  {
    slug: "stability-ball",
    name: "Stability ball",
    category: "accessories",
    sort: 45,
    description: "Core, mobility, and unstable surface options.",
  },
  {
    slug: "bosu",
    name: "BOSU / balance trainer",
    category: "accessories",
    sort: 46,
    description: "Balance and lower-leg stability work.",
  },
  {
    slug: "glute-ham",
    name: "GHD / glute-ham",
    category: "accessories",
    sort: 47,
    description: "Back extensions, GHD sit-ups, Nordic progressions.",
  },
  {
    slug: "rope-climb",
    name: "Climbing rope",
    category: "accessories",
    sort: 48,
    description: "Grip and upper-body climbing conditioning.",
  },
  {
    slug: "parallette",
    name: "Parallettes / push-up handles",
    category: "accessories",
    sort: 49,
    description: "Neutral-grip push-ups and L-sit work.",
  },
  {
    slug: "pvc-pipe",
    name: "PVC / dowel",
    category: "accessories",
    sort: 50,
    description: "Pattern practice, pass-throughs, and warm-up drills.",
  },
  {
    slug: "yoga-mat",
    name: "Mat / floor space",
    category: "accessories",
    sort: 51,
    description: "Floor mobility, core, and stretches.",
  },
  // Cardio
  {
    slug: "cardio-bike",
    name: "Bike (air / assault / spin)",
    category: "cardio",
    sort: 60,
    description: "Intervals and easy aerobic work.",
  },
  {
    slug: "rower",
    name: "Rowing erg",
    category: "cardio",
    sort: 61,
    description: "Full-body aerobic and interval work.",
  },
  {
    slug: "ski-erg",
    name: "SkiErg",
    category: "cardio",
    sort: 62,
    description: "Upper-body dominant conditioning.",
  },
  {
    slug: "treadmill",
    name: "Treadmill",
    category: "cardio",
    sort: 63,
    description: "Walk, incline, and run options.",
  },
  {
    slug: "stair-climber",
    name: "Stair climber / stepmill",
    category: "cardio",
    sort: 64,
    description: "Lower-body dense cardio.",
  },
  {
    slug: "elliptical",
    name: "Elliptical",
    category: "cardio",
    sort: 65,
    description: "Low-impact aerobic option.",
  },
  {
    slug: "jump-rope",
    name: "Jump rope",
    category: "cardio",
    sort: 66,
    description: "Portable conditioning and warm-up.",
  },
  {
    slug: "assault-runner",
    name: "Curved / assault runner",
    category: "cardio",
    sort: 67,
    description: "Self-powered sprint and aerobic work.",
  },
];

/** Specialty gear off by default for small-studio demo realism */
const DEFAULT_OFF = new Set([
  "smith",
  "landmine",
  "trap-bar",
  "rower",
  "ski-erg",
  "glute-ham",
  "sled",
  "battle-ropes",
  "rope-climb",
  "hack-squat",
  "assisted-pullup",
  "stair-climber",
  "sandbox-bag",
  "swiss-bar",
  "cable-crossover",
  "preacher-curl",
  "t-bar-row",
  "assault-runner",
  "parallette",
]);

const EXERCISES: EqDef[] = [
  // ── Mobility / corrective ──────────────────────────────────────────
  {
    slug: "thoracic-foam-roll",
    name: "Thoracic extension over foam roller",
    pattern: "mobility",
    muscles: "thoracic spine",
    tags: "shoulder,mobility,back-scratch,apley,tspine",
    equipment: ["foam-roller"],
    cues: "Support head; open chest over roller; breathe into extension.",
    difficulty: "beginner",
  },
  {
    slug: "wall-slides",
    name: "Wall slides",
    pattern: "mobility",
    muscles: "scapular stabilizers, serratus",
    tags: "shoulder,mobility,scapula,back-scratch",
    equipment: [],
    cues: "Low back and wrists on wall; slide without flaring ribs.",
    difficulty: "beginner",
  },
  {
    slug: "band-pull-aparts",
    name: "Band pull-aparts",
    pattern: "horizontal_pull",
    muscles: "rear delts, rhomboids",
    tags: "shoulder,posture,scapula,pull",
    equipment: ["bands"],
    difficulty: "beginner",
  },
  {
    slug: "face-pulls",
    name: "Cable face pulls",
    pattern: "horizontal_pull",
    muscles: "rear delts, external rotators",
    tags: "shoulder,posture,scapula,back-scratch",
    equipment: ["cable"],
    difficulty: "beginner",
  },
  {
    slug: "prone-yt",
    name: "Prone Y / T raises",
    pattern: "mobility",
    muscles: "lower traps, rear delts",
    tags: "shoulder,scapula,mobility,back-scratch",
    equipment: [],
    difficulty: "beginner",
  },
  {
    slug: "doorway-pec-stretch",
    name: "Doorway pec stretch",
    pattern: "mobility",
    muscles: "pec major/minor",
    tags: "shoulder,mobility,posture",
    equipment: [],
    difficulty: "beginner",
  },
  {
    slug: "open-book",
    name: "Open book rotation",
    pattern: "mobility",
    muscles: "thoracic rotators",
    tags: "mobility,tspine,shoulder",
    equipment: [],
    difficulty: "beginner",
  },
  {
    slug: "sleeper-stretch",
    name: "Sleeper stretch (gentle)",
    pattern: "mobility",
    muscles: "posterior shoulder",
    tags: "shoulder,mobility,ir,back-scratch",
    equipment: [],
    cues: "Pain-free only; no aggressive forcing.",
    difficulty: "beginner",
  },
  {
    slug: "cat-cow",
    name: "Cat-cow",
    pattern: "mobility",
    muscles: "spine mobility",
    tags: "mobility,spine,warmup",
    equipment: [],
    difficulty: "beginner",
  },
  {
    slug: "worlds-greatest-stretch",
    name: "World's greatest stretch",
    pattern: "mobility",
    muscles: "hips, T-spine, hamstrings",
    tags: "mobility,warmup,hip,tspine",
    equipment: [],
    difficulty: "beginner",
  },
  {
    slug: "90-90-hip-switch",
    name: "90/90 hip switches",
    pattern: "mobility",
    muscles: "hip rotators",
    tags: "mobility,hip,warmup",
    equipment: [],
    difficulty: "beginner",
  },
  {
    slug: "ankle-df-wall",
    name: "Ankle DF knee-to-wall",
    pattern: "mobility",
    muscles: "ankle dorsiflexors, soleus",
    tags: "mobility,ankle,squat,heels",
    equipment: [],
    cues: "Heel stays down; drive knee toward wall.",
    difficulty: "beginner",
  },
  {
    slug: "hip-flexor-kneeling",
    name: "Kneeling hip flexor opener",
    pattern: "mobility",
    muscles: "iliopsoas, rectus femoris",
    tags: "mobility,hip,posture,apt",
    equipment: [],
    difficulty: "beginner",
  },
  {
    slug: "thread-the-needle",
    name: "Thread the needle",
    pattern: "mobility",
    muscles: "thoracic rotators",
    tags: "mobility,tspine,shoulder",
    equipment: [],
    difficulty: "beginner",
  },
  {
    slug: "band-dislocates",
    name: "Band dislocates / pass-throughs",
    pattern: "mobility",
    muscles: "shoulders, T-spine",
    tags: "mobility,shoulder,warmup",
    equipment: ["bands"],
    difficulty: "beginner",
  },
  {
    slug: "pvc-pass-through",
    name: "PVC / stick pass-throughs",
    pattern: "mobility",
    muscles: "shoulders",
    tags: "mobility,shoulder,warmup",
    equipment: ["pvc-pipe", "bands"],
    equipmentAny: true,
    difficulty: "beginner",
  },
  {
    slug: "lacrosse-pec",
    name: "Pec soft tissue (ball)",
    pattern: "mobility",
    muscles: "pec minor/major",
    tags: "mobility,shoulder,soft-tissue",
    equipment: ["lacrosse-ball"],
    difficulty: "beginner",
  },

  // ── Squat pattern ──────────────────────────────────────────────────
  {
    slug: "goblet-squat",
    name: "Goblet squat",
    pattern: "squat",
    muscles: "quads, glutes",
    tags: "legs,squat,beginner",
    equipment: ["dumbbell", "kettlebell"],
    equipmentAny: true,
    difficulty: "beginner",
    cues: "Elbows inside knees; chest tall.",
  },
  {
    slug: "back-squat",
    name: "Barbell back squat",
    pattern: "squat",
    muscles: "quads, glutes",
    tags: "legs,squat,strength",
    equipment: ["barbell", "rack"],
    difficulty: "intermediate",
  },
  {
    slug: "front-squat",
    name: "Barbell front squat",
    pattern: "squat",
    muscles: "quads, core, glutes",
    tags: "legs,squat,strength,quad",
    equipment: ["barbell", "rack"],
    difficulty: "intermediate",
  },
  {
    slug: "box-squat",
    name: "Box squat",
    pattern: "squat",
    muscles: "quads, glutes",
    tags: "legs,squat,beginner,technique",
    equipment: ["box", "barbell", "dumbbell"],
    equipmentAny: true,
    difficulty: "beginner",
  },
  {
    slug: "split-squat",
    name: "Rear-foot elevated split squat",
    pattern: "squat",
    muscles: "quads, glutes",
    tags: "legs,unilateral,squat",
    equipment: ["dumbbell", "bench"],
    equipmentAny: true,
    difficulty: "intermediate",
  },
  {
    slug: "walking-lunge",
    name: "Walking lunges",
    pattern: "squat",
    muscles: "quads, glutes",
    tags: "legs,unilateral,lunge",
    equipment: ["dumbbell", "kettlebell"],
    equipmentAny: true,
    difficulty: "beginner",
  },
  {
    slug: "reverse-lunge",
    name: "Reverse lunges",
    pattern: "squat",
    muscles: "quads, glutes",
    tags: "legs,unilateral,lunge,knee-friendly",
    equipment: ["dumbbell", "kettlebell"],
    equipmentAny: true,
    difficulty: "beginner",
  },
  {
    slug: "lateral-lunge",
    name: "Lateral lunges",
    pattern: "squat",
    muscles: "glutes, adductors, quads",
    tags: "legs,unilateral,frontal",
    equipment: ["dumbbell", "kettlebell"],
    equipmentAny: true,
    difficulty: "beginner",
  },
  {
    slug: "step-up",
    name: "Step-ups",
    pattern: "squat",
    muscles: "quads, glutes",
    tags: "legs,unilateral,step",
    equipment: ["box", "dumbbell"],
    equipmentAny: true,
    difficulty: "beginner",
  },
  {
    slug: "leg-press",
    name: "Leg press",
    pattern: "squat",
    muscles: "quads, glutes",
    tags: "legs,squat,machine",
    equipment: ["leg-press"],
    difficulty: "beginner",
  },
  {
    slug: "hack-squat",
    name: "Hack squat",
    pattern: "squat",
    muscles: "quads, glutes",
    tags: "legs,squat,machine,quad",
    equipment: ["hack-squat"],
    difficulty: "intermediate",
  },
  {
    slug: "leg-extension",
    name: "Leg extension",
    pattern: "squat",
    muscles: "quads",
    tags: "legs,quad,machine,isolation",
    equipment: ["leg-extension"],
    difficulty: "beginner",
  },
  {
    slug: "bodyweight-squat",
    name: "Bodyweight squat",
    pattern: "squat",
    muscles: "quads, glutes",
    tags: "legs,squat,beginner,bodyweight",
    equipment: [],
    difficulty: "beginner",
  },
  {
    slug: "jump-squat",
    name: "Jump squats",
    pattern: "squat",
    muscles: "quads, glutes, calves",
    tags: "legs,power,plyometric",
    equipment: [],
    difficulty: "intermediate",
  },
  {
    slug: "smith-squat",
    name: "Smith machine squat",
    pattern: "squat",
    muscles: "quads, glutes",
    tags: "legs,squat,machine",
    equipment: ["smith"],
    difficulty: "beginner",
  },

  // ── Hinge ──────────────────────────────────────────────────────────
  {
    slug: "rdl-db",
    name: "Dumbbell Romanian deadlift",
    pattern: "hinge",
    muscles: "hamstrings, glutes",
    tags: "legs,hinge,posterior",
    equipment: ["dumbbell"],
    difficulty: "intermediate",
    cues: "Soft knees; hips back; bar/DBs close to legs.",
  },
  {
    slug: "bb-rdl",
    name: "Barbell Romanian deadlift",
    pattern: "hinge",
    muscles: "hamstrings, glutes",
    tags: "legs,hinge,strength",
    equipment: ["barbell"],
    difficulty: "intermediate",
  },
  {
    slug: "trap-bar-deadlift",
    name: "Trap bar deadlift",
    pattern: "hinge",
    muscles: "posterior chain, quads",
    tags: "legs,hinge,strength",
    equipment: ["trap-bar"],
    difficulty: "intermediate",
  },
  {
    slug: "conventional-deadlift",
    name: "Conventional deadlift",
    pattern: "hinge",
    muscles: "posterior chain, back, grip",
    tags: "legs,hinge,strength,pull",
    equipment: ["barbell"],
    difficulty: "advanced",
  },
  {
    slug: "kb-swing",
    name: "Kettlebell swing (Russian)",
    pattern: "hinge",
    muscles: "glutes, hamstrings, core",
    tags: "hinge,power,conditioning,kb",
    equipment: ["kettlebell"],
    cues: "Hinge, not squat; snap hips; arms relaxed.",
    difficulty: "intermediate",
  },
  {
    slug: "single-leg-rdl",
    name: "Single-leg RDL",
    pattern: "hinge",
    muscles: "hamstrings, glutes, balance",
    tags: "legs,hinge,unilateral",
    equipment: ["dumbbell", "kettlebell"],
    equipmentAny: true,
    difficulty: "intermediate",
  },
  {
    slug: "hip-thrust",
    name: "Barbell hip thrust",
    pattern: "hinge",
    muscles: "glutes",
    tags: "glutes,hinge,posterior",
    equipment: ["barbell", "bench"],
    difficulty: "intermediate",
  },
  {
    slug: "glute-bridge",
    name: "Glute bridge",
    pattern: "hinge",
    muscles: "glutes",
    tags: "glutes,beginner,hinge",
    equipment: [],
    difficulty: "beginner",
  },
  {
    slug: "leg-curl",
    name: "Leg curl",
    pattern: "hinge",
    muscles: "hamstrings",
    tags: "legs,hamstring,machine,isolation",
    equipment: ["leg-curl"],
    difficulty: "beginner",
  },
  {
    slug: "nordic-curl",
    name: "Nordic hamstring curl (assisted)",
    pattern: "hinge",
    muscles: "hamstrings",
    tags: "legs,hamstring,eccentric",
    equipment: [],
    difficulty: "advanced",
  },
  {
    slug: "good-morning",
    name: "Good morning (light)",
    pattern: "hinge",
    muscles: "hamstrings, erectors",
    tags: "hinge,posterior,technique",
    equipment: ["barbell"],
    difficulty: "intermediate",
  },
  {
    slug: "back-extension",
    name: "Back extension / GHD raise",
    pattern: "hinge",
    muscles: "erectors, glutes, hamstrings",
    tags: "posterior,hinge,back",
    equipment: ["glute-ham", "bench"],
    equipmentAny: true,
    difficulty: "beginner",
  },

  // ── Horizontal push ────────────────────────────────────────────────
  {
    slug: "push-up",
    name: "Push-up",
    pattern: "horizontal_push",
    muscles: "chest, triceps, anterior delts",
    tags: "push,chest,bodyweight",
    equipment: [],
    difficulty: "beginner",
  },
  {
    slug: "knee-push-up",
    name: "Knee push-up",
    pattern: "horizontal_push",
    muscles: "chest, triceps",
    tags: "push,chest,beginner,bodyweight",
    equipment: [],
    difficulty: "beginner",
  },
  {
    slug: "db-bench-press",
    name: "Dumbbell bench press",
    pattern: "horizontal_push",
    muscles: "chest, triceps",
    tags: "push,chest,strength",
    equipment: ["dumbbell", "bench"],
    difficulty: "intermediate",
  },
  {
    slug: "bb-bench-press",
    name: "Barbell bench press",
    pattern: "horizontal_push",
    muscles: "chest, triceps",
    tags: "push,chest,strength",
    equipment: ["barbell", "bench"],
    difficulty: "intermediate",
  },
  {
    slug: "incline-db-press",
    name: "Incline dumbbell press",
    pattern: "horizontal_push",
    muscles: "upper chest, triceps, delts",
    tags: "push,chest,incline",
    equipment: ["dumbbell", "bench"],
    difficulty: "intermediate",
  },
  {
    slug: "push-up-deficit",
    name: "Deficit / elevated push-up",
    pattern: "horizontal_push",
    muscles: "chest, triceps",
    tags: "push,chest,bodyweight",
    equipment: [],
    difficulty: "intermediate",
  },
  {
    slug: "machine-chest-press",
    name: "Machine chest press",
    pattern: "horizontal_push",
    muscles: "chest, triceps",
    tags: "push,chest,machine",
    equipment: ["chest-press-machine"],
    difficulty: "beginner",
  },
  {
    slug: "cable-fly",
    name: "Cable fly",
    pattern: "horizontal_push",
    muscles: "chest",
    tags: "push,chest,isolation",
    equipment: ["cable"],
    difficulty: "beginner",
  },
  {
    slug: "pec-deck",
    name: "Pec deck fly",
    pattern: "horizontal_push",
    muscles: "chest",
    tags: "push,chest,machine,isolation",
    equipment: ["pec-deck"],
    difficulty: "beginner",
  },
  {
    slug: "dips",
    name: "Parallel bar dips",
    pattern: "horizontal_push",
    muscles: "chest, triceps, anterior delts",
    tags: "push,chest,triceps,bodyweight",
    equipment: ["dip-bars"],
    difficulty: "intermediate",
  },
  {
    slug: "assisted-dip",
    name: "Assisted dips",
    pattern: "horizontal_push",
    muscles: "chest, triceps",
    tags: "push,chest,machine,beginner",
    equipment: ["assisted-pullup"],
    difficulty: "beginner",
  },
  {
    slug: "trx-push-up",
    name: "Suspension push-up",
    pattern: "horizontal_push",
    muscles: "chest, core, triceps",
    tags: "push,chest,suspension",
    equipment: ["suspension"],
    difficulty: "intermediate",
  },

  // ── Vertical push ──────────────────────────────────────────────────
  {
    slug: "db-ohp",
    name: "Dumbbell overhead press",
    pattern: "vertical_push",
    muscles: "delts, triceps",
    tags: "push,shoulders,overhead",
    equipment: ["dumbbell"],
    difficulty: "intermediate",
  },
  {
    slug: "bb-ohp",
    name: "Barbell overhead press",
    pattern: "vertical_push",
    muscles: "delts, triceps, core",
    tags: "push,shoulders,overhead,strength",
    equipment: ["barbell"],
    difficulty: "intermediate",
  },
  {
    slug: "landmine-press",
    name: "Landmine press",
    pattern: "vertical_push",
    muscles: "delts, triceps, core",
    tags: "push,shoulders,overhead,shoulder-friendly",
    equipment: ["landmine", "barbell"],
    equipmentAny: true,
    difficulty: "intermediate",
  },
  {
    slug: "half-kneeling-ohp",
    name: "Half-kneeling DB press",
    pattern: "vertical_push",
    muscles: "delts, core",
    tags: "push,shoulders,overhead,core",
    equipment: ["dumbbell"],
    difficulty: "beginner",
  },
  {
    slug: "machine-shoulder-press",
    name: "Machine shoulder press",
    pattern: "vertical_push",
    muscles: "delts, triceps",
    tags: "push,shoulders,machine",
    equipment: ["shoulder-press-machine"],
    difficulty: "beginner",
  },
  {
    slug: "lateral-raise",
    name: "Dumbbell lateral raise",
    pattern: "vertical_push",
    muscles: "lateral delts",
    tags: "shoulders,isolation",
    equipment: ["dumbbell"],
    difficulty: "beginner",
  },
  {
    slug: "cable-lateral-raise",
    name: "Cable lateral raise",
    pattern: "vertical_push",
    muscles: "lateral delts",
    tags: "shoulders,isolation",
    equipment: ["cable"],
    difficulty: "beginner",
  },
  {
    slug: "pike-push-up",
    name: "Pike push-up",
    pattern: "vertical_push",
    muscles: "delts, triceps",
    tags: "push,shoulders,bodyweight",
    equipment: [],
    difficulty: "intermediate",
  },

  // ── Horizontal pull ────────────────────────────────────────────────
  {
    slug: "db-row",
    name: "Single-arm dumbbell row",
    pattern: "horizontal_pull",
    muscles: "lats, rhomboids",
    tags: "pull,back,posture",
    equipment: ["dumbbell", "bench"],
    equipmentAny: true,
    difficulty: "beginner",
  },
  {
    slug: "cable-row",
    name: "Seated cable row",
    pattern: "horizontal_pull",
    muscles: "lats, mid-back",
    tags: "pull,back",
    equipment: ["cable"],
    difficulty: "beginner",
  },
  {
    slug: "machine-row",
    name: "Seated row machine",
    pattern: "horizontal_pull",
    muscles: "lats, mid-back",
    tags: "pull,back,machine",
    equipment: ["seated-row"],
    difficulty: "beginner",
  },
  {
    slug: "band-row",
    name: "Band row",
    pattern: "horizontal_pull",
    muscles: "mid-back, lats",
    tags: "pull,back,beginner",
    equipment: ["bands"],
    difficulty: "beginner",
  },
  {
    slug: "bb-bent-row",
    name: "Barbell bent-over row",
    pattern: "horizontal_pull",
    muscles: "lats, mid-back, erectors",
    tags: "pull,back,strength",
    equipment: ["barbell"],
    difficulty: "intermediate",
  },
  {
    slug: "chest-supported-row",
    name: "Chest-supported DB row",
    pattern: "horizontal_pull",
    muscles: "mid-back, rear delts",
    tags: "pull,back,posture",
    equipment: ["dumbbell", "bench"],
    difficulty: "beginner",
  },
  {
    slug: "trx-row",
    name: "Suspension row",
    pattern: "horizontal_pull",
    muscles: "mid-back, lats, core",
    tags: "pull,back,suspension,bodyweight",
    equipment: ["suspension"],
    difficulty: "beginner",
  },
  {
    slug: "meadows-row",
    name: "Landmine / Meadows row",
    pattern: "horizontal_pull",
    muscles: "lats, mid-back",
    tags: "pull,back",
    equipment: ["landmine", "barbell"],
    equipmentAny: true,
    difficulty: "intermediate",
  },
  {
    slug: "rear-delt-fly",
    name: "Rear delt fly (DB or machine)",
    pattern: "horizontal_pull",
    muscles: "rear delts",
    tags: "pull,shoulder,posture,isolation",
    equipment: ["dumbbell", "pec-deck"],
    equipmentAny: true,
    difficulty: "beginner",
  },

  // ── Vertical pull ──────────────────────────────────────────────────
  {
    slug: "pull-up",
    name: "Pull-up / chin-up",
    pattern: "vertical_pull",
    muscles: "lats, biceps",
    tags: "pull,back,bodyweight",
    equipment: ["pullup-bar"],
    difficulty: "intermediate",
  },
  {
    slug: "lat-pulldown",
    name: "Lat pulldown",
    pattern: "vertical_pull",
    muscles: "lats, biceps",
    tags: "pull,back",
    equipment: ["lat-pulldown"],
    difficulty: "beginner",
  },
  {
    slug: "assisted-pull-up",
    name: "Assisted pull-up",
    pattern: "vertical_pull",
    muscles: "lats, biceps",
    tags: "pull,back,beginner",
    equipment: ["assisted-pullup", "bands"],
    equipmentAny: true,
    difficulty: "beginner",
  },
  {
    slug: "straight-arm-pulldown",
    name: "Straight-arm pulldown",
    pattern: "vertical_pull",
    muscles: "lats",
    tags: "pull,back,isolation",
    equipment: ["cable"],
    difficulty: "beginner",
  },
  {
    slug: "band-pulldown",
    name: "Band pulldown / lat stretch pull",
    pattern: "vertical_pull",
    muscles: "lats",
    tags: "pull,back,beginner",
    equipment: ["bands"],
    difficulty: "beginner",
  },

  // ── Arms ───────────────────────────────────────────────────────────
  {
    slug: "db-curl",
    name: "Dumbbell biceps curl",
    pattern: "horizontal_pull",
    muscles: "biceps",
    tags: "arms,biceps,isolation",
    equipment: ["dumbbell"],
    difficulty: "beginner",
  },
  {
    slug: "hammer-curl",
    name: "Hammer curl",
    pattern: "horizontal_pull",
    muscles: "brachialis, biceps",
    tags: "arms,biceps,isolation",
    equipment: ["dumbbell"],
    difficulty: "beginner",
  },
  {
    slug: "ez-curl",
    name: "EZ-bar curl",
    pattern: "horizontal_pull",
    muscles: "biceps",
    tags: "arms,biceps",
    equipment: ["ez-bar", "barbell"],
    equipmentAny: true,
    difficulty: "beginner",
  },
  {
    slug: "triceps-pushdown",
    name: "Cable triceps pushdown",
    pattern: "horizontal_push",
    muscles: "triceps",
    tags: "arms,triceps,isolation",
    equipment: ["cable"],
    difficulty: "beginner",
  },
  {
    slug: "oh-triceps-ext",
    name: "Overhead triceps extension",
    pattern: "vertical_push",
    muscles: "triceps",
    tags: "arms,triceps,isolation",
    equipment: ["dumbbell", "cable"],
    equipmentAny: true,
    difficulty: "beginner",
  },
  {
    slug: "skull-crusher",
    name: "Skull crushers",
    pattern: "horizontal_push",
    muscles: "triceps",
    tags: "arms,triceps",
    equipment: ["ez-bar", "dumbbell", "barbell"],
    equipmentAny: true,
    difficulty: "intermediate",
  },

  // ── Core / carry ───────────────────────────────────────────────────
  {
    slug: "dead-bug",
    name: "Dead bug",
    pattern: "core",
    muscles: "deep core",
    tags: "core,stability",
    equipment: [],
    difficulty: "beginner",
  },
  {
    slug: "plank",
    name: "Front plank",
    pattern: "core",
    muscles: "core",
    tags: "core,stability",
    equipment: [],
    difficulty: "beginner",
  },
  {
    slug: "side-plank",
    name: "Side plank",
    pattern: "core",
    muscles: "obliques, glute med",
    tags: "core,stability,lateral",
    equipment: [],
    difficulty: "beginner",
  },
  {
    slug: "bird-dog",
    name: "Bird dog",
    pattern: "core",
    muscles: "core, posterior chain",
    tags: "core,stability,beginner",
    equipment: [],
    difficulty: "beginner",
  },
  {
    slug: "farmer-carry",
    name: "Farmer carry",
    pattern: "carry",
    muscles: "grip, traps, core",
    tags: "carry,conditioning",
    equipment: ["dumbbell", "kettlebell"],
    equipmentAny: true,
    difficulty: "beginner",
  },
  {
    slug: "suitcase-carry",
    name: "Suitcase carry",
    pattern: "carry",
    muscles: "obliques, grip, core",
    tags: "carry,core,unilateral",
    equipment: ["dumbbell", "kettlebell"],
    equipmentAny: true,
    difficulty: "beginner",
  },
  {
    slug: "overhead-carry",
    name: "Overhead carry",
    pattern: "carry",
    muscles: "shoulders, core",
    tags: "carry,shoulder,core",
    equipment: ["dumbbell", "kettlebell"],
    equipmentAny: true,
    difficulty: "intermediate",
  },
  {
    slug: "ab-wheel-rollout",
    name: "Ab wheel rollout",
    pattern: "core",
    muscles: "anterior core",
    tags: "core,anti-extension",
    equipment: ["ab-wheel"],
    difficulty: "intermediate",
  },
  {
    slug: "cable-pallof",
    name: "Pallof press",
    pattern: "core",
    muscles: "anti-rotation core",
    tags: "core,anti-rotation",
    equipment: ["cable", "bands"],
    equipmentAny: true,
    difficulty: "beginner",
  },
  {
    slug: "hanging-knee-raise",
    name: "Hanging knee raise",
    pattern: "core",
    muscles: "abs, hip flexors",
    tags: "core,abs",
    equipment: ["pullup-bar"],
    difficulty: "intermediate",
  },
  {
    slug: "cable-crunch",
    name: "Cable crunch",
    pattern: "core",
    muscles: "abs",
    tags: "core,abs",
    equipment: ["cable"],
    difficulty: "beginner",
  },
  {
    slug: "med-ball-slam",
    name: "Medicine ball slam",
    pattern: "core",
    muscles: "core, power",
    tags: "core,power,conditioning",
    equipment: ["medicine-ball", "slam-ball"],
    equipmentAny: true,
    difficulty: "beginner",
  },
  {
    slug: "russian-twist",
    name: "Russian twist (controlled)",
    pattern: "core",
    muscles: "obliques",
    tags: "core,rotation",
    equipment: ["medicine-ball", "dumbbell"],
    equipmentAny: true,
    difficulty: "beginner",
  },
  {
    slug: "dead-bug-press",
    name: "Dead bug with press",
    pattern: "core",
    muscles: "core, shoulders",
    tags: "core,stability",
    equipment: ["dumbbell", "bands"],
    equipmentAny: true,
    difficulty: "beginner",
  },

  // ── Glute / hip machines ───────────────────────────────────────────
  {
    slug: "hip-abduction-machine",
    name: "Hip abduction machine",
    pattern: "squat",
    muscles: "glute med",
    tags: "glutes,hip,machine,lateral",
    equipment: ["hip-abductor"],
    difficulty: "beginner",
  },
  {
    slug: "hip-adduction-machine",
    name: "Hip adduction machine",
    pattern: "squat",
    muscles: "adductors",
    tags: "hip,machine",
    equipment: ["hip-adductor"],
    difficulty: "beginner",
  },
  {
    slug: "band-side-walk",
    name: "Band lateral monster walks",
    pattern: "squat",
    muscles: "glute med",
    tags: "glutes,hip,warmup,band",
    equipment: ["bands"],
    difficulty: "beginner",
  },
  {
    slug: "clamshell",
    name: "Side-lying clamshell",
    pattern: "mobility",
    muscles: "glute med",
    tags: "glutes,hip,beginner,warmup",
    equipment: ["bands"],
    equipmentAny: true,
    difficulty: "beginner",
  },
  {
    slug: "calf-raise",
    name: "Standing calf raise",
    pattern: "squat",
    muscles: "gastrocnemius, soleus",
    tags: "calves,legs",
    equipment: ["calf-raise-machine", "dumbbell", "smith"],
    equipmentAny: true,
    difficulty: "beginner",
  },

  // ── Cardio / conditioning ──────────────────────────────────────────
  {
    slug: "bike-intervals",
    name: "Bike intervals",
    pattern: "cardio",
    muscles: "conditioning",
    tags: "cardio,conditioning,fat-loss",
    equipment: ["cardio-bike"],
    difficulty: "beginner",
  },
  {
    slug: "rower-intervals",
    name: "Rower intervals",
    pattern: "cardio",
    muscles: "conditioning",
    tags: "cardio,conditioning",
    equipment: ["rower"],
    difficulty: "beginner",
  },
  {
    slug: "ski-erg-intervals",
    name: "SkiErg intervals",
    pattern: "cardio",
    muscles: "conditioning, upper pull",
    tags: "cardio,conditioning",
    equipment: ["ski-erg"],
    difficulty: "beginner",
  },
  {
    slug: "treadmill-incline-walk",
    name: "Incline treadmill walk",
    pattern: "cardio",
    muscles: "conditioning, calves, glutes",
    tags: "cardio,fat-loss,liss",
    equipment: ["treadmill"],
    difficulty: "beginner",
  },
  {
    slug: "jump-rope",
    name: "Jump rope",
    pattern: "cardio",
    muscles: "conditioning, calves",
    tags: "cardio,conditioning,warmup",
    equipment: ["jump-rope"],
    difficulty: "beginner",
  },
  {
    slug: "sled-push",
    name: "Sled push",
    pattern: "cardio",
    muscles: "legs, conditioning",
    tags: "conditioning,legs,sled",
    equipment: ["sled"],
    difficulty: "beginner",
  },
  {
    slug: "sled-pull",
    name: "Sled drag / pull",
    pattern: "cardio",
    muscles: "posterior chain, conditioning",
    tags: "conditioning,posterior,sled",
    equipment: ["sled"],
    difficulty: "beginner",
  },
  {
    slug: "battle-ropes",
    name: "Battle rope waves",
    pattern: "cardio",
    muscles: "conditioning, shoulders, core",
    tags: "conditioning,cardio",
    equipment: ["battle-ropes"],
    difficulty: "beginner",
  },
  {
    slug: "stair-climber",
    name: "Stair climber steady",
    pattern: "cardio",
    muscles: "conditioning, legs",
    tags: "cardio,fat-loss,liss",
    equipment: ["stair-climber"],
    difficulty: "beginner",
  },
  {
    slug: "elliptical",
    name: "Elliptical easy",
    pattern: "cardio",
    muscles: "conditioning",
    tags: "cardio,liss,low-impact",
    equipment: ["elliptical"],
    difficulty: "beginner",
  },
  {
    slug: "box-step-overs",
    name: "Box step-overs",
    pattern: "cardio",
    muscles: "legs, conditioning",
    tags: "conditioning,legs",
    equipment: ["box"],
    difficulty: "beginner",
  },
  {
    slug: "assault-bike-intervals",
    name: "Assault / air bike intervals",
    pattern: "cardio",
    muscles: "conditioning",
    tags: "cardio,conditioning,hiit,fat-loss",
    equipment: ["cardio-bike"],
    difficulty: "intermediate",
  },
  {
    slug: "curved-runner",
    name: "Curved runner intervals",
    pattern: "cardio",
    muscles: "conditioning, legs",
    tags: "cardio,conditioning,sprint",
    equipment: ["assault-runner"],
    difficulty: "intermediate",
  },

  // ── Extra squat / hinge / push-pull coverage ────────────────────────
  {
    slug: "wall-sit",
    name: "Wall sit",
    pattern: "squat",
    muscles: "quads",
    secondary: "glutes, core",
    tags: "legs,isometric,beginner,rehab",
    equipment: [],
    difficulty: "beginner",
    description: "Isometric quad endurance — useful warm-up or finisher.",
  },
  {
    slug: "heel-elevated-squat",
    name: "Heel-elevated squat",
    pattern: "squat",
    muscles: "quads, glutes",
    tags: "legs,squat,quad,ankle",
    equipment: ["weight-plate", "dumbbell"],
    equipmentAny: true,
    difficulty: "beginner",
    description: "Elevated heels free the ankles and bias quads.",
  },
  {
    slug: "sumo-goblet-squat",
    name: "Sumo goblet squat",
    pattern: "squat",
    muscles: "quads, glutes, adductors",
    tags: "legs,squat,sumo,beginner",
    equipment: ["dumbbell", "kettlebell"],
    equipmentAny: true,
    difficulty: "beginner",
  },
  {
    slug: "sumo-deadlift",
    name: "Sumo deadlift",
    pattern: "hinge",
    muscles: "posterior chain, glutes, adductors",
    tags: "legs,hinge,strength,sumo",
    equipment: ["barbell"],
    difficulty: "intermediate",
  },
  {
    slug: "cable-pull-through",
    name: "Cable pull-through",
    pattern: "hinge",
    muscles: "glutes, hamstrings",
    tags: "hinge,glutes,beginner",
    equipment: ["cable"],
    difficulty: "beginner",
  },
  {
    slug: "kb-deadlift",
    name: "Kettlebell deadlift",
    pattern: "hinge",
    muscles: "posterior chain, grip",
    tags: "hinge,beginner,kb",
    equipment: ["kettlebell"],
    difficulty: "beginner",
    description: "Teaching hinge with a KB between the feet.",
  },
  {
    slug: "floor-press",
    name: "Dumbbell floor press",
    pattern: "horizontal_push",
    muscles: "chest, triceps",
    tags: "push,chest,shoulder-friendly",
    equipment: ["dumbbell"],
    difficulty: "beginner",
    description: "Limited ROM press — shoulder-friendly lockout strength.",
  },
  {
    slug: "incline-bb-press",
    name: "Incline barbell press",
    pattern: "horizontal_push",
    muscles: "upper chest, triceps, delts",
    tags: "push,chest,incline,strength",
    equipment: ["barbell", "bench"],
    difficulty: "intermediate",
  },
  {
    slug: "close-grip-push-up",
    name: "Close-grip push-up",
    pattern: "horizontal_push",
    muscles: "triceps, chest",
    tags: "push,triceps,bodyweight",
    equipment: [],
    difficulty: "intermediate",
  },
  {
    slug: "arnold-press",
    name: "Arnold press",
    pattern: "vertical_push",
    muscles: "delts, triceps",
    tags: "push,shoulders,hypertrophy",
    equipment: ["dumbbell"],
    difficulty: "intermediate",
  },
  {
    slug: "seated-db-ohp",
    name: "Seated dumbbell overhead press",
    pattern: "vertical_push",
    muscles: "delts, triceps",
    tags: "push,shoulders",
    equipment: ["dumbbell", "bench"],
    difficulty: "beginner",
  },
  {
    slug: "seal-row",
    name: "Seal / prone bench row",
    pattern: "horizontal_pull",
    muscles: "mid-back, rear delts",
    tags: "pull,back,posture",
    equipment: ["dumbbell", "barbell", "bench"],
    equipmentAny: true,
    difficulty: "intermediate",
  },
  {
    slug: "inverted-row",
    name: "Inverted row / bodyweight row",
    pattern: "horizontal_pull",
    muscles: "mid-back, lats, biceps",
    tags: "pull,back,bodyweight,beginner",
    equipment: ["pullup-bar", "suspension", "rack"],
    equipmentAny: true,
    difficulty: "beginner",
    description: "Scalable horizontal pull — feet placement adjusts difficulty.",
  },
  {
    slug: "chin-up",
    name: "Chin-up",
    pattern: "vertical_pull",
    muscles: "lats, biceps",
    tags: "pull,back,bodyweight,biceps",
    equipment: ["pullup-bar"],
    difficulty: "intermediate",
  },
  {
    slug: "neutral-grip-pull-up",
    name: "Neutral-grip pull-up",
    pattern: "vertical_pull",
    muscles: "lats, biceps",
    tags: "pull,back,bodyweight,shoulder-friendly",
    equipment: ["pullup-bar"],
    difficulty: "intermediate",
  },
  {
    slug: "single-arm-lat-pulldown",
    name: "Single-arm lat pulldown",
    pattern: "vertical_pull",
    muscles: "lats",
    tags: "pull,back,unilateral",
    equipment: ["lat-pulldown", "cable"],
    equipmentAny: true,
    difficulty: "beginner",
  },
  {
    slug: "preacher-curl",
    name: "Preacher curl",
    pattern: "horizontal_pull",
    muscles: "biceps",
    tags: "arms,biceps,isolation",
    equipment: ["preacher-curl", "ez-bar", "dumbbell"],
    equipmentAny: true,
    difficulty: "beginner",
  },
  {
    slug: "cable-curl",
    name: "Cable biceps curl",
    pattern: "horizontal_pull",
    muscles: "biceps",
    tags: "arms,biceps,isolation",
    equipment: ["cable"],
    difficulty: "beginner",
  },
  {
    slug: "copenhagen-plank",
    name: "Copenhagen plank (adductor)",
    pattern: "core",
    muscles: "adductors, core",
    tags: "core,adductor,stability,injury-prevention",
    equipment: ["bench"],
    difficulty: "advanced",
    description: "Side plank variant loading adductors — progress carefully.",
  },
  {
    slug: "hollow-hold",
    name: "Hollow body hold",
    pattern: "core",
    muscles: "anterior core",
    tags: "core,gymnastics,isometric",
    equipment: [],
    difficulty: "intermediate",
  },
  {
    slug: "cable-woodchop",
    name: "Cable woodchop / chop",
    pattern: "core",
    muscles: "obliques, core",
    tags: "core,rotation,power",
    equipment: ["cable"],
    difficulty: "beginner",
  },
  {
    slug: "rack-carry",
    name: "Front rack carry (KB/DB)",
    pattern: "carry",
    muscles: "core, upper back, legs",
    tags: "carry,core,conditioning",
    equipment: ["kettlebell", "dumbbell"],
    equipmentAny: true,
    difficulty: "intermediate",
  },
  {
    slug: "front-rack-carry",
    name: "Barbell front rack walk",
    pattern: "carry",
    muscles: "core, quads, upper back",
    tags: "carry,core,strength",
    equipment: ["barbell"],
    difficulty: "advanced",
  },
  {
    slug: "seated-calf-raise",
    name: "Seated calf raise",
    pattern: "squat",
    muscles: "soleus",
    tags: "calves,legs,isolation",
    equipment: ["calf-raise-machine", "dumbbell"],
    equipmentAny: true,
    difficulty: "beginner",
  },

  // ── Plyometric / power ─────────────────────────────────────────────
  {
    slug: "box-jump",
    name: "Box jump",
    pattern: "plyometric",
    muscles: "quads, glutes, calves",
    tags: "power,plyometric,legs",
    equipment: ["box"],
    difficulty: "intermediate",
    description: "Low-complexity power — step down to spare eccentrics.",
  },
  {
    slug: "broad-jump",
    name: "Broad jump",
    pattern: "plyometric",
    muscles: "posterior chain, quads",
    tags: "power,plyometric,legs,bodyweight",
    equipment: [],
    difficulty: "intermediate",
  },
  {
    slug: "pogo-hops",
    name: "Pogo hops / ankle hops",
    pattern: "plyometric",
    muscles: "calves, ankles",
    tags: "power,plyometric,warmup,ankles",
    equipment: [],
    difficulty: "beginner",
  },
  {
    slug: "med-ball-chest-pass",
    name: "Med ball chest pass",
    pattern: "plyometric",
    muscles: "chest, triceps, power",
    tags: "power,plyometric,push",
    equipment: ["medicine-ball"],
    difficulty: "beginner",
  },
  {
    slug: "kb-snatch",
    name: "Kettlebell snatch",
    pattern: "plyometric",
    muscles: "posterior chain, shoulders, grip",
    tags: "power,kb,conditioning,advanced",
    equipment: ["kettlebell"],
    difficulty: "advanced",
    description: "Ballistic single-arm pull to overhead — coach technique first.",
  },
  {
    slug: "sandbag-clean",
    name: "Sandbag clean to shoulder",
    pattern: "hinge",
    muscles: "posterior chain, core, grip",
    tags: "odd-object,conditioning,hinge",
    equipment: ["sandbox-bag"],
    difficulty: "intermediate",
    cues: "Hinge to bag; explode to shoulder; catch soft; switch sides.",
  },
  {
    slug: "swiss-bar-bench",
    name: "Swiss / multi-grip bar press",
    pattern: "horizontal_push",
    muscles: "chest, triceps",
    tags: "push,chest,shoulder-friendly",
    equipment: ["swiss-bar", "bench"],
    difficulty: "intermediate",
    description: "Neutral-ish grip press for shoulder-friendly loading.",
    cues: "Set scapulae; press smooth; own lockout without shrug.",
  },
  {
    slug: "trx-ytw",
    name: "Suspension Y-T-W raises",
    pattern: "mobility",
    muscles: "lower traps, rear delts, rhomboids",
    tags: "shoulder,scapula,posture,mobility",
    equipment: ["suspension"],
    difficulty: "beginner",
    cues: "Lean back lightly; raise arms into Y, T, then W; control.",
  },
];

let librarySeedPromise: Promise<void> | null = null;

/**
 * Idempotent library seed — upserts equipment + exercises by slug
 * so existing DBs receive catalog expansions on next app load.
 */
export async function seedLibraryIfNeeded() {
  if (!librarySeedPromise) {
    librarySeedPromise = runLibrarySeed().catch((err) => {
      librarySeedPromise = null;
      throw err;
    });
  }
  await librarySeedPromise;
}

async function runLibrarySeed() {
  const db = await getDb();
  const equipIdBySlug = new Map<string, string>();

  // ── Equipment upsert by slug ───────────────────────────────────────
  for (const e of EQUIPMENT) {
    const [existing] = await db
      .select()
      .from(equipmentItems)
      .where(eq(equipmentItems.slug, e.slug))
      .limit(1);

    const sortOrder = Math.trunc(e.sort);
    if (existing) {
      await db
        .update(equipmentItems)
        .set({
          name: e.name,
          category: e.category,
          sortOrder,
          description: e.description || null,
        })
        .where(eq(equipmentItems.id, existing.id));
      equipIdBySlug.set(e.slug, existing.id);
    } else {
      const eid = id("eq");
      equipIdBySlug.set(e.slug, eid);
      try {
        await db.insert(equipmentItems).values({
          id: eid,
          slug: e.slug,
          name: e.name,
          category: e.category,
          sortOrder,
          description: e.description || null,
        });
      } catch {
        // Race / unique on slug — re-select and update
        const [again] = await db
          .select()
          .from(equipmentItems)
          .where(eq(equipmentItems.slug, e.slug))
          .limit(1);
        if (!again) throw new Error(`Failed to insert equipment: ${e.slug}`);
        await db
          .update(equipmentItems)
          .set({
            name: e.name,
            category: e.category,
            sortOrder,
            description: e.description || null,
          })
          .where(eq(equipmentItems.id, again.id));
        equipIdBySlug.set(e.slug, again.id);
      }
    }
  }

  // ── Exercises upsert by slug ───────────────────────────────────────
  let sort = 0;
  for (const ex of EXERCISES) {
    const eqIds = ex.equipment
      .map((s) => equipIdBySlug.get(s))
      .filter((x): x is string => !!x);

    const [existing] = await db
      .select()
      .from(exercises)
      .where(eq(exercises.slug, ex.slug))
      .limit(1);

    const difficulty = ex.difficulty || "intermediate";
    const description =
      ex.description ||
      EXERCISE_DESCRIPTIONS[ex.slug] ||
      defaultExerciseDescription({
        name: ex.name,
        pattern: ex.pattern,
        muscles: ex.muscles,
        difficulty,
      });
    const cues =
      ex.cues || EXERCISE_CUES[ex.slug] || defaultExerciseCues(ex.pattern);
    const secondary =
      ex.secondary || EXERCISE_SECONDARY[ex.slug] || "";

    const values = {
      name: ex.name,
      description,
      movementPattern: ex.pattern,
      primaryMuscles: ex.muscles,
      secondaryMuscles: secondary,
      difficulty,
      tags: ex.tags,
      cues,
      equipmentIds: eqIds,
      equipmentAny: ex.equipmentAny ?? false,
      active: true,
      sortOrder: sort++,
    };

    if (existing) {
      await db.update(exercises).set(values).where(eq(exercises.id, existing.id));
    } else {
      await db.insert(exercises).values({
        id: id("ex"),
        organizationId: null,
        slug: ex.slug,
        ...values,
      });
    }
  }

  await ensureOrgEquipmentRows();
}

/** Ensure every org has a row per catalog item (new gear defaults). */
async function ensureOrgEquipmentRows() {
  const db = await getDb();
  const orgs = await db.select().from(organizations);
  const catalog = await db.select().from(equipmentItems);
  if (!catalog.length || !orgs.length) return;

  for (const org of orgs) {
    const existing = await db
      .select()
      .from(orgEquipment)
      .where(eq(orgEquipment.organizationId, org.id));
    const have = new Set(existing.map((r) => r.equipmentId));

    for (const item of catalog) {
      if (item.slug === "bodyweight") continue;
      if (have.has(item.id)) continue;
      try {
        await db.insert(orgEquipment).values({
          id: id("oe"),
          organizationId: org.id,
          equipmentId: item.id,
          available: !DEFAULT_OFF.has(item.slug),
          notes: null,
        });
      } catch {
        // unique race
      }
    }
  }
}
